### ISSUE TITLE
Lack of information about the mode of operation

### ISSUE THREAD

**Issue by J9B10** [CorvusCodex/Multithread-Ethereum-Brute-Force#1]
Very interesting project.

But it lacks information about some things like:

1º: Which address format to use?
Start with "0x" or Without "0x"?

2º: What is the search mode?
Does it look for part of the address as with vanity generators?
Or do you search by full address?

I did some tests, but I couldn't figure out what the operation mode is because it doesn't return an error code about whether the user data entered is correct or wrong.

It's good that you update the README.md with this information and cite examples of how to enter the data correctly.

I thank.

**Comment by CorvusCodex** [comment]
Hello,
Huge thanks for feedback! 

i have edited the README.md and app.js

i have added the example data.txt to repo and edited app.js 

`// Reading data from a file named 'data.txt'
const data = fs.readFileSync('./data.txt');
// Splitting the data by new line and adding each address to the Set
data.toString().split("\n").forEach(address => {
    if (address.startsWith('0x')) {
        addresses.add(address);
    } else {
        console.error('Error: addresses are not in correct format. Addresses must start with 0x');
        process.exit(1);
    }
});`
