### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by sushack-Developement** [CorvusCodex/Multithread-Ethereum-Brute-Force#2]
it displays ┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by CorvusCodex** [comment]
The problem is fixed in the new update.

**Comment by CorvusCodex** [comment]
.
